PREFIX my: <http://example.org/ApplicationSchema#>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
SELECT ?mspatialAccuracy
WHERE {
  my:A geo:hasGeometry ?aGeom .
  ?aGeom geo:hasMetricSpatialAccuracy ?mspatialAccuracy .
}
